on: [push, workflow_dispatch]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    name: Runs e2e tests with Playwright
    steps:
      - name: Pull test service container
        uses: docker pull jclem/playwright-test-service-prototype:latest
      - name: Create output directory
        run: mkdir -p "$RUNNER_TEMP/artifacts"
      - name: Run test service
        run: |
          docker run jclem/playwright-test-service-prototype \
            --mount source="$RUNNER_TEMP/artifacts",destination=/app/artifacts
      - name: upload artifacts
        if: ${{ always() }} # could be if: ${{ failure() }} to only upload artifacts when previous step of running playwright tests fails
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '$RUNNER_TEMP/artifact/results.json'
